### ISSUE TITLE
IntInterval and FloatInterval crash when input is not of the same type.

### ISSUE THREAD

**Issue by IlianIliev** [kvesteri/intervals#41]
Verified both with Python 2 and Python 3.

If I want to check if a specific number is in an interval and the number type does not match that of the interval an exception is raised (check examples below).

I can except the case when `float` is not in `IntInterval` because the floating point numbers does not belong to the set of integers, but then the result should be `False` not an exception.
As for 'int' in 'FloatInterval' as the real numbers set include the integer numbers set then it should return true no matter if we pass integer or float.

P.S. I would be happy to work on a fix )
```
>>> from intervals import IntInterval, FloatInterval
>>> ii = IntInterval.from_string('[0, 30)')
>>> 5 in ii
True
>>> 5.0 in ii
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ilian/.virtualenvs/tmp-d04ae033510398ee/lib/python3.6/site-packages/intervals/interval.py", line 101, in wrapper
    return func(self, arg)
  File "/Users/ilian/.virtualenvs/tmp-d04ae033510398ee/lib/python3.6/site-packages/intervals/interval.py", line 438, in __contains__
    if self.upper_inc or (not self.upper_inc and not other.upper_inc)
AttributeError: 'float' object has no attribute 'upper_inc'
>>>
```

And for `FloatInterval`
```
>>> fi = FloatInterval.from_string('[0, 30)')
>>> 5.0 in fi
True
>>> 5 in fi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ilian/.virtualenvs/tmp-d04ae033510398ee/lib/python3.6/site-packages/intervals/interval.py", line 101, in wrapper
    return func(self, arg)
  File "/Users/ilian/.virtualenvs/tmp-d04ae033510398ee/lib/python3.6/site-packages/intervals/interval.py", line 438, in __contains__
    if self.upper_inc or (not self.upper_inc and not other.upper_inc)
AttributeError: 'int' object has no attribute 'upper_inc'
```

**Comment by kvesteri** [comment]
Fixed as of 0.8.1
